spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:workshop
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 5
      idleTimeout: 30000
      poolName: workshop
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
