spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/workshop
    username: workshop
    password: workshop
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: never
    hikari:
      maximumPoolSize: 5
      idleTimeout: 30000
      poolName: workshop
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
