spring:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

  flyway:
    enabled: false

server:
  error:
    include-message: always
    include-stacktrace: never
